### ISSUE TITLE
Do zrobienia

### ISSUE THREAD

**Issue by MichalKlimczak35** [perciax/eiti-porr#1]
Udało mi się doprowadzić program aby liczył przez około 4 minut  ( tyle chciał Karbowski )
Rzeczy, które chciałbym abyś zrobił/poprawił:
- wektor x (ten na końcu) drukuje się zawsze mimo flagi --debug=false naszym zadanie nie jest sprawdzanie poprawności równania ale zbadanie czasu wykonywania się programu.
- Czy to działa jako program sekwencyjny czy zrównoleglony - potrzebujemy obu wersji aby mieć porównanie.
- Czas powinien być możliwy do ustawienia z poziomu flagi np.: Time=1 to sekundy 2 to milisekundy 3 to mickosekundy.
- nie potrzebujemy czasu wczytywania tylko czasu wykonywania
- jak istnieją inne tryby zrównoleglania z pamięcią wspólną to czy mógłbyś je jakoś dodać jako flagi?

**Comment by perciax** [comment]
Zrobione.

plik ge - eliminacja gaussa
plik gje - eliminacja gaussa - jordana

po wywołaniu ./gje bez nazwy pliku wyświetla się Usage

GJE: 
flaga --quiet=true, wycisza całe drukowanie poza czasem obliczeń
flaga --time="seconds", formatuje wyjście z timera
flaga --parallel=true, pusza obliczenia na wszystkich rdzeniach równolegle

różnice czasową na korzyść zrównoleglania, zauważylem dopiero przy zadaniu 100x100
